### ISSUE TITLE
io.js readable-streams WG meeting

### ISSUE THREAD

**Issue by chrisdickinson** [iojs/readable-stream#106]
~~I've put together a [doodle](https://doodle.com/5srxwvsk6sbz2evz) that proposes an hour long meeting for wednesday (1/28), thursday (1/29), or friday (1/30). If those dates don't work, I can reopen for next week.~~

**UTC Wed 30-Jan-15 17:00:**

San Francisco: Wed 28-Jan-15 09:00
Amsterdam: Wed 28-Jan-15 18:00
Moscow: Wed 28-Jan-15 20:00
Sydney: Thu 29-Jan-15 04:00

cc @iojs/streams 

**Public Youtube feed**: http://www.youtube.com/watch?v=I9nDOSGfwZg
**Agenda and minutes doc**, (eventually) editable by WG: https://docs.google.com/document/d/17aTgLnjMXIrfjgNaTUnHQO7m3xgzHR2VXBTmi03Qii4/edit#

**Agenda So Far**:

Extracted from https://github.com/iojs/readable-stream/labels/wg-agenda prior to meeting.

* adopt a charter [#105](https://github.com/iojs/readable-stream/issues/105)
* release and versioning strategy [#101](https://github.com/iojs/readable-stream/issues/101)
* simpler stream creation [#102](https://github.com/iojs/readable-stream/issues/102)
* proposal: deprecate implicit flowing of streams [#99](https://github.com/iojs/readable-stream/issues/99)

**Comment by mikeal** [comment]
could I sit in on this one as well?

**Comment by sonewman** [comment]
I have put some times in, the difficulty I have is that the best times for you guys is mostly 7pm onwards for me which is a little tricky since I have to commute from London, and when i get back I have to look after my daughter. I'm not sure what the google hangouts app is like for iPhone, but I guess i'll let you know :smile:

**Comment by rvagg** [comment]
![screen shot 2015-01-28 at 9 08 33 am](https://cloud.githubusercontent.com/assets/495647/5928199/5716e476-a6cd-11e4-82f1-7c2089860270.png)

You're killing me @sonewman, your availability is all 5am for me.

Actually, hangouts is great on mobile, and you don't have to have video turned on of course.

**Comment by sonewman** [comment]
@rvagg ahh, we have a 11 hour time difference :stuck_out_tongue_winking_eye: I could do it in work hours, since my work is pretty flexible about this sort of thing, but I can't select anything between 4am and 6pm. 

Your availability is 9pm to 4am. I guess i could set my alarm... for 3am... :sleeping:

**Comment by rvagg** [comment]
my availability goes much later than that, my best cross-over with GMT is late night for me but that's no good for PST; we have this problem @ NodeSource except that our main GMT(ish) person has abnormal working hours so it ends up working out fine.

**Comment by chrisdickinson** [comment]
@mikeal Go for it!

@sonewman @rvagg Sorry about that – if this week doesn't work out we can try again for early next week. 

[The charter](https://github.com/iojs/readable-stream/issues/105) is the biggest item I'd like to cover for this meeting, since that sets the tone for the kinds of changes we can make in the near-term future – so definitely make your feelings known on that issue.

**Comment by rvagg** [comment]
I don't mind missing out if it doesn't line up, it seems like @sonewman might have more energy and time to devote here than I do. I would like discussion of #101 though as I haven't published matching readable-stream releases for the recent 0.10 and 0.11 releases and we need to decide how to handle that, if at all, there's a general expectation out there that readable-stream keep up with core, particularly bugs fixed in core (https://github.com/joyent/node/pull/7856 not withstanding).

**Comment by sonewman** [comment]
@chrisdickinson it looks like the timing is ok for @rvagg, i think the problem is just me. 

I have a lot of commitments in the evenings (having a 2 year old) & when I am up and about it's the middle of the night for you guys.

I'll let you decide.

The alternative is that you pick a time and if I make it I make it, if it ends up being 4am (for me) perhaps I will just be really early for work that morning!

Otherwise I can watch the highlights on my way to work and post my thoughts etc.

**Comment by sonewman** [comment]
- I say 2 year old, she is actually 2 next Tuesday

**Comment by chrisdickinson** [comment]
We're still missing a few responses (@isaacs, @timgestson, @Raynos), but it looks like we'll be doing this at 9AM PST on the Friday, January 30th.

**Comment by Raynos** [comment]
I filled out the doodle. I don't know whether I can usefully contribute to this meeting though.

**Comment by chrisdickinson** [comment]
Ok, it looks like Friday 9am PST it is.

**Comment by isaacs** [comment]
I'm in.

**Comment by mafintosh** [comment]
@chrisdickinson is it still friday? the post says it was yesterday

**Comment by chrisdickinson** [comment]
@mafintosh Ack! good catch. Fixed. It's Jan 30th, 17:00 UTC.

**Comment by timgestson** [comment]
Might be a few minutes late, but I'm in as well.

**Comment by calvinmetcalf** [comment]
Im in

**Comment by isaacs** [comment]
Ack, I'm sorry, everyone, emergency just came up and I have to bail.  Since I was literally just added to this group, maybe next time can be my official start?

**Comment by chrisdickinson** [comment]
@isaacs We'll catch you next time. If you have the time, it'd be great to get your thoughts on  [the charter](https://github.com/iojs/readable-stream/issues/105) (if not, that's totally okay, too!)

**Comment by sonewman** [comment]
@isaacs Ah, that sucks. I hope it's nothing serious.

**Comment by sonewman** [comment]
@chrisdickinson do you need any contact details from me?

**Comment by chrisdickinson** [comment]
PR is up: https://github.com/iojs/readable-stream/pull/110

**Comment by sonewman** [comment]
Hey, so what's next? Do we have a plan for another meeting?

**Comment by mikeal** [comment]
Are there any issues of contention? Are there any burning questions people want to discuss?

**Comment by calvinmetcalf** [comment]
If anyone who hasn't yet wants to weigh in on #109,  #111, #112, #113, or #114

**Comment by sonewman** [comment]
@calvinmetcalf I'm sorry I must say I have had a lot on lately (...sparing the life story) I will go have a read :smile:

**Comment by mscdex** [comment]
+1 to discussing #111 in a meeting soon :-)

**Comment by chrisdickinson** [comment]
Closing this, going to schedule a new meeting.

**Comment by sonewman** [comment]
awesome :smile:
